### ISSUE TITLE
減量案

### ISSUE THREAD

**Issue by da0ka** [Hiru-ge/Co-fitting-static#1]
local環境で動作すれば事足りるはず。index.htmlで言えば11～14、17～34、207～221行の記述が無駄に思えてなりません

**Comment by Hiru-ge** [comment]
本変換器は、プログラムに関する知識がない人の利用を視野に入れており、そのためlocalではなくWebサイト上での動作をメインとして想定しています。
今回焦点が当たっていた点は「Google AdSense」と「Google Fonts」に関連する部分でした。
Google Fontsはともかく、AdSense部分は本質に関係ない部分であるにもかかわらず行数が多く、コードの可読性・理解へのハードルに悪影響を及ぼしていると思われました。よってAdSense部分のみを削除しました。
助言ありがとうございます。
